name: 副班提醒服务
on:
  schedule:
    # 每天上午10:25检查 (UTC+8 北京时间)
    - cron: '25 2 * * *'  # 每天 UTC 2:25 = 北京时间10:25
  workflow_dispatch:  # 允许手动触发测试
jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: 智能副班提醒
        run: |
          # 获取当前日期和星期几
          CURRENT_DAY=$(date +%u)  # 1=周一, 7=周日
          CURRENT_HOUR=$(date +%H)
          
          echo "当前时间: $(date)"
          echo "星期: $CURRENT_DAY"
          echo "小时: $CURRENT_HOUR"
          
          # 判断今天是否上3:00-11:00班次 (在10:30时正在上班)
          if [ "$CURRENT_HOUR" = "10" ]; then
            echo "当前是10点，正在上3:00-11:00班次"
            
            # 判断是否是周五(5)或周日(7)
            if [ "$CURRENT_DAY" = "5" ] || [ "$CURRENT_DAY" = "7" ]; then
              echo "今天是周五或周日，发送副班提醒..."
              
              # 根据星期几确定明日班次
              if [ "$CURRENT_DAY" = "5" ]; then
                TOMORROW_MSG="周六"
              else
                TOMORROW_MSG="周一"
              fi
              
              curl -X POST \
                -H "Content-Type: application/json" \
                -d "{\"msgtype\":\"text\",\"text\":{\"content\":\"注意：明日($TOMORROW_MSG)上副班，请做好准备。\"}}" \
                "https://oapi.dingtalk.com/robot/send?access_token=c965583b00a0f7184e546e662b6902b0fdfab31b110d56249a45c7921e28defc"
              
              echo "副班提醒已发送"
            else
              echo "今天不是周五或周日，不发送提醒"
            fi
          else
            echo "当前不是10点，不在3:00-11:00班次工作时间"
          fi
