name: 京博网校专项提醒
on:
  schedule:
    # 2025年10月30日上午9:00执行 (UTC+8 北京时间)
    - cron: '0 1 30 10 *'  # 每年10月30日 UTC 1:00 = 北京时间9:00
  workflow_dispatch:  # 允许手动触发测试
jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: 发送京博网校专项提醒
        run: |
          # 获取当前日期
          CURRENT_YEAR=$(date +%Y)
          CURRENT_DATE=$(date +%m-%d)
          TARGET_DATE="2025-10-30"
          
          echo "当前时间: $(date)"
          echo "当前年份: $CURRENT_YEAR"
          echo "当前日期: $CURRENT_DATE"
          echo "目标日期: $TARGET_DATE"
          
          # 判断是否是目标日期（2025年10月30日）
          if [ "$(date +%Y-%m-%d)" = "$TARGET_DATE" ] || [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
            echo "🎯 到达目标日期，发送京博网校专项提醒..."
            
            curl -X POST -H "Content-Type: application/json" \
              -d '{"msgtype":"text","text":{"content":"注意：京博网校基质沥青材料运行部质量风险管理标准-赵培辉 截至10.31 13:00，请确认是否完成"}}' \
              "https://oapi.dingtalk.com/robot/send?access_token=c965583b00a0f7184e546e662b6902b0fdfab31b110d56249a45c7921e28defc"
            
            echo "✅ 京博网校专项提醒已发送"
          else
            echo "⏳ 未到目标日期，跳过发送"
          fi
