name: 企安e学提醒

on:
  schedule:
    # 每天在11:30执行一次
    - cron: '30 3 * * *'  # UTC时间3:30 = 北京时间11:30
  workflow_dispatch:
    inputs:
      test_date:
        description: '测试日期 (YYYY-MM-DD)'
        required: false
        default: ''

jobs:
  enterprise-e-learning-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: 企安e学提醒
        run: |
          # 设置时区
          export TZ='Asia/Shanghai'
          
          # 处理手动输入的测试日期
          if [ -n "${{ github.event.inputs.test_date }}" ]; then
            TEST_DATE="${{ github.event.inputs.test_date }}"
            echo "使用测试日期: $TEST_DATE"
            CURRENT_DATE=$TEST_DATE
          else
            CURRENT_DATE=$(date +%Y-%m-%d)
          fi
          
          CURRENT_DAY=$(date -d "$CURRENT_DATE" +%d)   # 日期
          CURRENT_MONTH=$(date -d "$CURRENT_DATE" +%m) # 月份
          CURRENT_YEAR=$(date -d "$CURRENT_DATE" +%Y)  # 年份
          CURRENT_TIME=$(date +%H:%M)
          
          echo "当前时间(北京时间): $(date)"
          echo "当前日期: $CURRENT_DATE"
          echo "当前时分: $CURRENT_TIME"
          echo "当前日期号: $CURRENT_DAY"
          
          # 定义提醒日期和内容
          declare -A REMINDER_DAYS=(
            ["13"]="注意：企安e学还剩2天截止（15日），请未完成的同事尽快完成「已完成」。"
            ["14"]="注意：企安e学明天截止（15日），请尚未完成的同事务必今天内完成「已完成」。"
            ["15"]="注意：今天是企安e学反馈最后期限（15日），请未完成的同事立即完成「已完成」。"
          )
          
          # 检查是否是提醒日期
          SHOULD_REMIND=false
          REMINDER_CONTENT=""
          
          for day_key in "${!REMINDER_DAYS[@]}"; do
            if [ "$CURRENT_DAY" = "$day_key" ]; then
              SHOULD_REMIND=true
              REMINDER_CONTENT="${REMINDER_DAYS[$day_key]}"
              break
            fi
          done
          
          # 创建标记文件路径，用于记录今天是否已经发送过提醒
          MARKER_FILE="/tmp/enterprise_e_learning_reminder_${CURRENT_DATE}.marker"
          
          if [ "$SHOULD_REMIND" = true ]; then
            echo "✅ 今天是提醒日期 ($CURRENT_DAY号)，发送企安e学提醒"
            
            # 检查是否今天已经发送过提醒
            if [ -f "$MARKER_FILE" ]; then
              echo "⏰ 今天已经发送过企安e学提醒，跳过重复提醒"
            else
              echo "✅ 发送企安e学提醒..."
              
              # 构建完整消息
              FULL_CONTENT="📚 工作提醒\n$REMINDER_CONTENT\n⏰ 提醒时间：$CURRENT_TIME\n📅 当前日期：$CURRENT_DATE"
              
              # 发送钉钉提醒（使用你提供的直接URL）
              curl -X POST -H "Content-Type: application/json" \
                -d "{
                  \"msgtype\": \"text\",
                  \"text\": {
                    \"content\": \"$FULL_CONTENT\"
                  }
                }" \
                "https://oapi.dingtalk.com/robot/send?access_token=c965583b00a0f7184e546e662b6902b0fdfab31b110d56249a45c7921e28defc"
              
              # 创建标记文件，表示今天已经发送过提醒
              touch "$MARKER_FILE"
              echo "✅ 企安e学提醒已发送，并创建标记文件防止重复提醒"
            fi
          else
            echo "⏳ 今天不是企安e学提醒日期"
            
            # 如果不在提醒日期内，删除标记文件（如果存在）
            if [ -f "$MARKER_FILE" ]; then
              rm "$MARKER_FILE"
              echo "🗑️ 删除标记文件，准备下一次提醒"
            fi
          fi
