name: 企安e学进度催办
on:
  schedule:
    # 从每月13日开始，每天上午10:00提醒，直到15日
    - cron: '0 2 13-15 * *'  # 每月13-15号 UTC 2:00 = 北京时间10:00
  workflow_dispatch:  # 允许手动触发测试
jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: 发送企安e学催办提醒
        run: |
          # 获取当前日期
          CURRENT_DAY=$(date +%d)
          DAYS_LEFT=$((15 - CURRENT_DAY))
          
          echo "当前日期: $CURRENT_DAY"
          echo "剩余天数: $DAYS_LEFT"
          
          # 根据剩余天数生成不同的提醒内容
          if [ "$DAYS_LEFT" -eq 2 ]; then
            MESSAGE="注意：企安e学还剩2天截止（15日），请未完成的同事尽快完成「已完成」。"
          elif [ "$DAYS_LEFT" -eq 1 ]; then
            MESSAGE="注意：企安e学明天截止（15日），请尚未完成的同事务必今天内完成「已完成」。"
          elif [ "$DAYS_LEFT" -eq 0 ]; then
            MESSAGE="注意：今天是企安e学反馈最后期限（15日），请未完成的同事立即完成「已完成」。"
          else
            MESSAGE="注意：企安e学请未完成的同事尽快完成「已完成」。"
          fi
          
          curl -X POST -H "Content-Type: application/json" -d "{\"msgtype\":\"text\",\"text\":{\"content\":\"$MESSAGE\"}}" "https://oapi.dingtalk.com/robot/send?access_token=c965583b00a0f7184e546e662b6902b0fdfab31b110d56249a45c7921e28defc"
          
          echo "催办提醒已发送: $MESSAGE"
