name: 泵设备切换提醒
on:
  schedule:
    # 每月15号和30号中午12点执行 (UTC+8 北京时间)
    - cron: '0 4 15 * *'  # 每月15号 UTC 4:00 = 北京时间12:00
    - cron: '0 4 30 * *'  # 每月30号 UTC 4:00 = 北京时间12:00
  workflow_dispatch:  # 允许手动触发测试
jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: 发送泵设备切换提醒
        run: |
          # 获取当前日期
          CURRENT_DATE=$(date +"%Y-%m-%d")
          echo "执行日期: $CURRENT_DATE"
          
          # 发送钉钉消息
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"msgtype":"text","text":{"content":"注意：减一泵切至工频泵，运行24小时切回"}}' \
          "https://oapi.dingtalk.com/robot/send?access_token=c965583b00a0f7184e546e662b6902b0fdfab31b110d56249a45c7921e28defc"
          
          echo "提醒消息已发送"
