name: 月度设备检查提醒
on:
  schedule:
    # 每月最后一天下午3点执行 (UTC+8 北京时间)
    - cron: '0 7 28-31 * *'  # 每月28-31号 UTC 7:00 = 北京时间15:00
  workflow_dispatch:  # 允许手动触发测试
jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: 检查是否为当月最后一天并发送提醒
        run: |
          # 获取当前日期和下一个月的第一天
          CURRENT_DAY=$(date +%d)
          NEXT_DAY=$(date -d "tomorrow" +%d)
          
          # 如果明天是1号，那么今天就是最后一天 或者 是手动触发
          if [ "$NEXT_DAY" = "01" ] || [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "发送提醒（最后一天或手动触发）..."
            curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"msgtype":"text","text":{"content":"注意：机泵盘车、特种设备巡检每月最后一天11：00班下班前上交给设备员。"}}' \
            "https://oapi.dingtalk.com/robot/send?access_token=c965583b00a0f7184e546e662b6902b0fdfab31b110d56249a45c7921e28defc"
            echo "提醒消息已发送"
          else
            echo "今天不是当月最后一天，跳过发送"
          fi
