name: 月度设备检查提醒
on:
  schedule:
    # 每月最后一天下午3点执行 (UTC+8 北京时间)
    - cron: '0 7 28-31 * *'  # 每月28-31号 UTC 7:00 = 北京时间15:00
  workflow_dispatch:  # 允许手动触发测试
jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: 检查是否为当月最后一天并判断班次发送提醒
        run: |
          # 获取当前日期和下一个月的第一天
          CURRENT_DAY=$(date +%d)
          NEXT_DAY=$(date -d "tomorrow" +%d)
          CURRENT_HOUR=$(date +%H)
          
          echo "当前时间: $(date)"
          echo "今天日期: $CURRENT_DAY"
          echo "明天日期: $NEXT_DAY"
          echo "当前小时: $CURRENT_HOUR"
          
          # 判断今天是否是当月最后一天
          if [ "$NEXT_DAY" = "01" ] || [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
            echo "今天是当月最后一天或手动触发"
            
            # 判断当前是否在上班（下午3点在11:00-20:00班次）
            if [ "$CURRENT_HOUR" = "15" ]; then
              echo "当前是下午3点，正在上11:00-20:00班次，发送提醒..."
              curl -X POST \
              -H "Content-Type: application/json" \
              -d '{"msgtype":"text","text":{"content":"注意：机泵盘车、特种设备巡检每月最后一天11：00班下班前上交给设备员。"}}' \
              "https://oapi.dingtalk.com/robot/send?access_token=c965583b00a0f7184e546e662b6902b0fdfab31b110d56249a45c7921e28defc"
              echo "提醒消息已发送"
            else
              echo "当前不是下午3点，不在11:00-20:00班次工作时间，跳过发送"
            fi
          else
            echo "今天不是当月最后一天，跳过发送"
          fi
