name: 多时段智能提醒
on:
  schedule:
    - cron: '*/10 16-23 * * *'
    - cron: '*/10 0-15 * * *'
  workflow_dispatch:
    inputs:
      test_time:
        description: '测试时间 (HH:MM)'
        required: false
        default: ''

jobs:
  发送提醒:
    runs-on: ubuntu-latest
    steps:
      - name: 多时段智能提醒
        env:
          钉钉Token: cfe74c285e2e30b46133eef62def804d28baef0d681a81ee0fdd1958fb13c877
        run: |
          # 设置时区
          export TZ='Asia/Shanghai'
          
          # 处理手动输入的测试时间
          if [ -n "${{ github.event.inputs.test_time }}" ]; then
            测试时间="${{ github.event.inputs.test_time }}"
            echo "使用测试时间: $测试时间"
            当前小时=$(echo $测试时间 | cut -d: -f1)
            当前分钟=$(echo $测试时间 | cut -d: -f2)
            当前时间=$测试时间
          else
            当前小时=$(date +%H)
            当前分钟=$(date +%M)
            当前时间=$(date +%H:%M)
          fi
          
          当前日期=$(date +%Y-%m-%d)
          当前星期=$(date +%u)
          echo "当前时间(北京时间): $(date)"
          echo "当前日期: $当前日期"
          echo "当前时分: $当前时间"
          
          # 修正日期计算 - 使用固定日期计算
          起始日期="2024-10-27"
          今天日期=$(date +%Y-%m-%d)
          
          # 计算天数差
          天数差=$(( ($(date -d "$今天日期" +%s) - $(date -d "$起始日期" +%s)) / 86400 ))
          周期位置=$((天数差 % 4))
          
          echo "从起始日相差天数: $天数差"
          echo "周期位置: $周期位置 (0=甲班, 1=休班, 2=乙班, 3=丙班)"
          
          # 判断今日班次
          case $周期位置 in
            0)
              今日班次="甲班 20:00-03:00"
              是否上班=true
              ;;
            1)
              今日班次="休班"
              是否上班=false
              ;;
            2)
              今日班次="乙班 03:00-11:00"
              是否上班=true
              ;;
            3)
              今日班次="丙班 11:00-20:00"
              是否上班=true
              ;;
          esac
          
          echo "今日班次: $今日班次"
          
          # 定义提醒时间点配置
          declare -A 提醒时间表=(
            ["00:00"]="🕛 注意：线上巡检按时进行"
            ["02:00"]="🕑 注意：线上巡检按时进行" 
            ["04:00"]="🕓 注意：线上巡检按时进行"
            ["06:00"]="🕕 注意：线上巡检按时进行"
            ["08:00"]="🕗 注意：线上巡检按时进行"
            ["10:00"]="🕙 注意：线上巡检按时进行"
            ["12:00"]="🕛 注意：线上巡检按时进行"
            ["14:00"]="🕑 注意：线上巡检按时进行"
            ["16:00"]="🕓 注意：线上巡检按时进行"
            ["18:00"]="🕕 注意：线上巡检按时进行"
            ["20:30"]="🕣 注意：线上巡检按时进行"
            ["22:00"]="🕙 注意：线上巡检按时进行"
          )
          
          # 检查是否在提醒时间点的前后5分钟内
          是否提醒=false
          目标时间=""
          提醒内容=""
          
          for 时间点 in "${!提醒时间表[@]}"; do
            目标小时=$(echo $时间点 | cut -d: -f1)
            目标分钟=$(echo $时间点 | cut -d: -f2)
            
            目标总分钟=$((10#$目标小时 * 60 + 10#$目标分钟))
            当前总分钟=$((10#$当前小时 * 60 + 10#$当前分钟))
            时间差=$((当前总分钟 - 目标总分钟))
            
            # 前后5分钟窗口
            if [ $时间差 -ge -5 ] && [ $时间差 -le 5 ] && [ $时间差 -ne 0 ]; then
              是否提醒=true
              目标时间=$时间点
              提醒内容="${提醒时间表[$时间点]}"
              
              # 判断是前5分钟还是后5分钟
              if [ $时间差 -lt 0 ]; then
                时间方向="前"
                相差分钟=$((0 - $时间差))
              else
                时间方向="后" 
                相差分钟=$时间差
              fi
              
              break
            fi
          done
          
          if [ "$是否提醒" = true ] && [ "$是否上班" = true ]; then
            echo "⏰ 在提醒时间窗口内: $目标时间 ($时间方向${相差分钟}分钟)"
            echo "✅ 今日上班，发送提醒..."
            
            # 添加星期信息
            星期数组=("周一" "周二" "周三" "周四" "周五" "周六" "周日")
            星期索引=$((当前星期 - 1))
            星期信息="${星期数组[$星期索引]}"
            
            # 构建完整的提醒内容
            if [ "$时间方向" = "前" ]; then
              提醒类型="⏰ 即将到达巡检时段"
            else
              提醒类型="⏰ 已过巡检时段"
            fi
            
            完整内容="$提醒内容\n$提醒类型\n📅 $当前日期 $星期信息\n👨‍💼 今日班次：$今日班次\n🎯 目标时间：$目标时间\n⏱️ 当前时间：$当前时间"
            
            # 发送钉钉提醒
            curl -X POST -H "Content-Type: application/json" \
              -d "{\"msgtype\":\"text\",\"text\":{\"content\":\"$完整内容\"}}" \
              "https://oapi.dingtalk.com/robot/send?access_token=$钉钉Token"
            
            echo "✅ 提醒已发送"
          elif [ "$是否提醒" = true ] && [ "$是否上班" = false ]; then
            echo "⏰ 在提醒时间窗口内，但今日休班，跳过提醒"
          else
            echo "⏳ 不在任何提醒时间窗口内"
          fi
