name: 精准常一泵切换提醒
on:
  schedule:
    # 每天上午9:26检查 (UTC+8 北京时间)
    - cron: '26 1 * * *'  # 每天 UTC 01:26 = 北京时间9:26
  workflow_dispatch:  # 允许手动触发测试
jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: 精准常一泵切换提醒
        run: |
          # 设置时区为北京时间
          export TZ='Asia/Shanghai'
          
          # 获取当前日期信息（北京时间）
          CURRENT_DATE=$(date +%Y-%m-%d)
          CURRENT_DAY=$(date +%u)  # 1=周一, 5=周五, 7=周日
          CURRENT_HOUR=$(date +%H)
          CURRENT_MINUTE=$(date +%M)
          CURRENT_TIME=$(date)
          
          echo "当前时间(北京时间): $CURRENT_TIME"
          echo "日期: $CURRENT_DATE"
          echo "星期: $CURRENT_DAY"
          echo "当前小时: $CURRENT_HOUR"
          echo "当前分钟: $CURRENT_MINUTE"
          
          # 基于4天严格循环的排班判断
          # 起点：2025-10-17 = 3:00-11:00
          # 循环：3:00-11:00 → 11:00-20:00 → 20:00-3:00 → 休息 → 循环
          START_DATE="2025-10-17"  # 这是一个3:00-11:00班的日子
          
          # 计算从起点开始的天数差
          START_SECONDS=$(date -d "$START_DATE" +%s)
          CURRENT_SECONDS=$(date -d "$CURRENT_DATE" +%s)
          DAYS_DIFF=$(( (CURRENT_SECONDS - START_SECONDS) / 86400 ))
          
          echo "距离起点天数差: $DAYS_DIFF"
          
          # 计算在4天循环中的位置
          CYCLE_POSITION=$(( (DAYS_DIFF % 4 + 4) % 4 ))
          
          echo "循环位置: $CYCLE_POSITION"
          
          # 根据循环位置确定班次
          case $CYCLE_POSITION in
            0)
              TODAY_SHIFT="3:00-11:00"
              ;;
            1)
              TODAY_SHIFT="11:00-20:00"
              ;;
            2)
              TODAY_SHIFT="20:00-3:00"
              ;;
            3)
              TODAY_SHIFT="休息"
              ;;
            *)
              TODAY_SHIFT="未知"
              ;;
          esac
          
          echo "今日班次: $TODAY_SHIFT"
          
          # 调试信息：显示未来几天的排班
          echo "=== 未来几天排班预览 ==="
          for i in 0 1 2 3 4 5 6; do
            FUTURE_DATE=$(date -d "$CURRENT_DATE +$i days" +%Y-%m-%d)
            FUTURE_SECONDS=$(date -d "$FUTURE_DATE" +%s)
            FUTURE_DAYS_DIFF=$(( (FUTURE_SECONDS - START_SECONDS) / 86400 ))
            FUTURE_POSITION=$(( (FUTURE_DAYS_DIFF % 4 + 4) % 4 ))
            
            case $FUTURE_POSITION in
              0) FUTURE_SHIFT="3:00-11:00" ;;
              1) FUTURE_SHIFT="11:00-20:00" ;;
              2) FUTURE_SHIFT="20:00-3:00" ;;
              3) FUTURE_SHIFT="休息" ;;
              *) FUTURE_SHIFT="未知" ;;
            esac
            
            echo "$FUTURE_DATE: $FUTURE_SHIFT"
          done
          echo "========================"
          
          # 判断是否发送提醒（只在3:00-11:00班的周一/周五9:26发送）
          if [ "$TODAY_SHIFT" = "3:00-11:00" ] && [ "$CURRENT_HOUR" = "09" ] && [ "$CURRENT_MINUTE" = "26" ]; then
            echo "✅ 满足提醒条件：当前上3:00-11:00班，且是上午9:26(北京时间)"
            
            # 周一常一泵切换提醒（变频）
            if [ "$CURRENT_DAY" = "1" ]; then
              echo "📢 今天是周一，发送常一泵变频切换提醒..."
              curl -X POST -H "Content-Type: application/json" \
                -d '{"msgtype":"text","text":{"content":"🔔 精准常一泵切换提醒 🔔\n注意：今日周一，请将常一泵切换至变频运行模式。\n当前班次：3:00-11:00\n提醒时间：9:26"}}' \
                "https://oapi.dingtalk.com/robot/send?access_token=c965583b00a0f7184e546e662b6902b0fdfab31b110d56249a45c7921e28defc"
              echo "✅ 周一常一泵变频提醒已发送"
            
            # 周五常一泵切换提醒（工频）
            elif [ "$CURRENT_DAY" = "5" ]; then
              echo "📢 今天是周五，发送常一泵工频切换提醒..."
              curl -X POST -H "Content-Type: application/json" \
                -d '{"msgtype":"text","text":{"content":"🔔 精准常一泵切换提醒 🔔\n注意：今日周五，请将常一泵切换至工频运行模式。\n当前班次：3:00-11:00\n提醒时间：9:26"}}' \
                "https://oapi.dingtalk.com/robot/send?access_token=c965583b00a0f7184e546e662b6902b0fdfab31b110d56249a45c7921e28defc"
              echo "✅ 周五常一泵工频提醒已发送"
            else
              echo "ℹ️ 今天不是周一或周五，不发送常一泵切换提醒"
            fi
          else
            echo "❌ 不满足提醒条件：班次=$TODAY_SHIFT, 小时=$CURRENT_HOUR, 分钟=$CURRENT_MINUTE"
            echo "📋 需要条件：班次=3:00-11:00 且 时间=09:26(北京时间)"
          fi
