name: 精准常一泵切换提醒
on:
  schedule:
    # 每天上午6:55检查 (UTC+8 北京时间)
    - cron: '55 22 * * *'  # 每天 UTC 22:55 = 北京时间6:55
  workflow_dispatch:  # 允许手动触发测试
jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: 精准常一泵切换提醒
        run: |
          # 获取当前日期信息
          CURRENT_DATE=$(date +%Y-%m-%d)
          CURRENT_DAY=$(date +%u)  # 1=周一, 5=周五, 7=周日
          CURRENT_HOUR=$(date +%H)
          
          echo "当前时间: $(date)"
          echo "日期: $CURRENT_DATE"
          echo "星期: $CURRENT_DAY"
          echo "当前小时: $CURRENT_HOUR"
          
          # 基于排班表的精准班次判断
          if [ "$CURRENT_DATE" = "2024-02-14" ]; then
            TODAY_SHIFT="11:00-20:00"
          elif [ "$CURRENT_DATE" = "2024-02-15" ]; then
            TODAY_SHIFT="20:00-3:00"
          elif [ "$CURRENT_DATE" = "2024-02-16" ]; then
            TODAY_SHIFT="休息"
          elif [ "$CURRENT_DATE" = "2024-02-17" ]; then
            TODAY_SHIFT="3:00-11:00"
          elif [ "$CURRENT_DATE" = "2024-02-18" ]; then
            TODAY_SHIFT="11:00-20:00"
          elif [ "$CURRENT_DATE" = "2024-02-19" ]; then
            TODAY_SHIFT="20:00-3:00"
          elif [ "$CURRENT_DATE" = "2024-02-20" ]; then
            TODAY_SHIFT="休息"
          elif [ "$CURRENT_DATE" = "2024-02-21" ]; then
            TODAY_SHIFT="3:00-11:00"
          else
            TODAY_SHIFT="未知"
          fi
          
          echo "今日班次: $TODAY_SHIFT"
          
          # 判断是否发送提醒（只在3:00-11:00班的周一/周五7点发送）
          if [ "$TODAY_SHIFT" = "3:00-11:00" ] && [ "$CURRENT_HOUR" = "7" ]; then
            echo "当前上3:00-11:00班，且是上午7点"
            
            # 周一常一泵切换提醒（变频）
            if [ "$CURRENT_DAY" = "1" ]; then
              echo "今天是周一，发送常一泵变频切换提醒..."
              curl -X POST -H "Content-Type: application/json" \
                -d '{"msgtype":"text","text":{"content":"注意：今日周一，请将常一泵切换至变频运行模式。"}}' \
                "https://oapi.dingtalk.com/robot/send?access_token=c965583b00a0f7184e546e662b6902b0fdfab31b110d56249a45c7921e28defc"
              echo "周一常一泵变频提醒已发送"
            
            # 周五常一泵切换提醒（工频）
            elif [ "$CURRENT_DAY" = "5" ]; then
              echo "今天是周五，发送常一泵工频切换提醒..."
              curl -X POST -H "Content-Type: application/json" \
                -d '{"msgtype":"text","text":{"content":"注意：今日周五，请将常一泵切换至工频运行模式。"}}' \
                "https://oapi.dingtalk.com/robot/send?access_token=c965583b00a0f7184e546e662b6902b0fdfab31b110d56249a45c7921e28defc"
              echo "周五常一泵工频提醒已发送"
            else
              echo "今天不是周一或周五，不发送常一泵切换提醒"
            fi
          else
            echo "不满足提醒条件：班次=$TODAY_SHIFT, 小时=$CURRENT_HOUR"
          fi
